
[build-system]
# Core dependencies
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

# --------------------------

[project]
name = "oh-my-gui"  # Project name
version = "1.2.0"           # project ver
authors = [
  { name="FishgameStudio", email="popxhxh@outlook.com" }
]
description = "A lightweight GUI library wrapping PySide6 for Python"  # Short description
readme = "README.md"         # Project doc
license = { file="LICENSE" } # License file
requires-python = ">=3.8"   # minimum python ver.
keywords = ["python", "gui", "oh-my-gui"]  # Project keyword

# Dependencies
dependencies = [
  "pyside6>=6.11.1",
  "pyperclip>=1.11.0", 
  "requests>=2.32.5"
]

classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]


[tool.setuptools]

packages = ["ohmygui"]